### PR TITLE
Create app.py

### PR DESCRIPTION
**Pull request by harshitajha4680**
# To-Do List Application

This is a simple to-do list application built using Flask, a lightweight and flexible Python web framework. The application provides a user-friendly interface for managing daily tasks, allowing users to create, edit, and delete tasks effortlessly.

## Key Features

- Real-time Task Management: Users can seamlessly add, edit, and delete tasks, enhancing productivity and organization.
- Responsive Design: The application adapts to various screen sizes, ensuring a consistent user experience on both desktop and mobile devices.
- Server-side Processing: Flask handles the server-side logic, delivering efficient performance and smooth interactions.

### CODE REVIEW

**Comment by harshitajha4680** [comment]
This is a simple to-do list application built using Flask, a lightweight and flexible Python web framework. The application provides a user-friendly interface for managing daily tasks, allowing users to create, edit, and delete tasks effortlessly. @Ro706

**Comment by Ro706** [comment]
@harshitajha4680 I need to create a pull request in this repository?

**Comment by harshitajha4680** [comment]
Yes

**Comment by harshitajha4680** [comment]
Please accept the pull request and merge it in the main

**Comment by Ro706** [comment]
@harshitajha4680  Is it ok ??
I Create a pull request
Screenshot 2024-10-11 010809
image

**Comment by harshitajha4680** [comment]
ok thank you so much!

**Comment by harshitajha4680** [comment]
thanks @Ro706

**Comment by harshitajha4680** [comment]
@hackelite01 please merge this PR!

**Comment by Ro706** [comment]
This PR is already Merged @harshitajha4680  ,....you want i push the code in **todo_app** folder?

**Pull request merged**
